services:
  api:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 8081:8081
    environment:
      - PGUSER=${DB_USER}
      - PGHOST=${DB_HOST}
      - PGDATABASE=${DB_NAME}
      - PGPORT=${DB_PORT}
      - PGPASSWORD=${DB_PASSWORD}
    networks:
      - user-history-local-network
      - shared-network

  db:
    image: postgres:16
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - user-history-local-network

networks:
  shared-network:
    name: "shared_network"
  user-history-local-network:
    name: "user_history_local_network"
